/* ========================================
   作品数据
   ======================================== */
const WORKS_DATA = [
    {
        id: 27,
        name: "Kohong — Maya角色动画短片",
        category: "animation",
        subCategory: "Character Animation",
        year: "2024",
        thumbnail: "assets/works/maya-anim-kohong/thumbnail.png",
        video: "assets/works/maya-anim-kohong/kohong.mp4",
        images: [],
        description: "大二上学期独立创作的Maya角色动画短片，从角色建模、骨骼绑定到动画曲线调节的全流程创作。",
        detailDescription: "Kohong是大二上学期独立完成的Maya角色动画课程作品，通过完整的CG动画制作管线展现了角色动画的综合能力。\\n\\n制作流程涵盖：\\n• 角色建模 — 在Maya中完成原创角色的三维模型搭建\\n• 骨骼绑定 — 为角色建立合理的骨骼层级与控制器系统\\n• 蒙皮权重 — 精细调整角色蒙皮，确保关节运动时的自然形变\\n• 动画调节 — 运用Graph Editor进行动画曲线精修，打磨关键帧与过渡帧\\n• 渲染输出 — 最终序列帧渲染并合成为完整动画短片\\n\\n该作品展现了从零开始制作一段完整角色动画的扎实基本功，涵盖Maya动画管线的核心环节。",
        software: ["Maya", "After Effects"],
        role: "角色建模 · 骨骼绑定 · 动画制作 · 渲染合成"
    },
    {
        id: 26,
        name: "鲜厨 — 美食菜谱App UI设计",
        category: "other",
        subCategory: "UI Design",
        year: "2025",
        thumbnail: "assets/works/food-app-ui/06-home.png",
        video: "",
        images: [
            "assets/works/food-app-ui/05-splash.png",
            "assets/works/food-app-ui/06-home.png",
            "assets/works/food-app-ui/01-profile.png",
            "assets/works/food-app-ui/10-menu-diary.png",
            "assets/works/food-app-ui/08-recipe-sidebar.png",
            "assets/works/food-app-ui/02-recipe-detail.png",
            "assets/works/food-app-ui/09-video-player.png",
            "assets/works/food-app-ui/03-grocery-list.png",
            "assets/works/food-app-ui/04-scan.png",
            "assets/works/food-app-ui/07-scan-camera.png",
            "assets/works/food-app-ui/11-comments.png",
            "assets/works/food-app-ui/12-share-input.png",
            "assets/works/food-app-ui/13-settings-diet.png",
            "assets/works/food-app-ui/14-settings-profile.png",
            "assets/works/food-app-ui/15-about-faq.png"
        ],
        description: "大二下学期小组UI设计作品——「鲜厨」美食菜谱类移动端App界面设计与落地制作，涵盖从用户研究到高保真原型的完整UI流程。",
        detailDescription: "鲜厨是大二下学期小组合作完成的UI设计课程作品，本人负责全部UI界面的落地制作与高保真原型输出。项目定位为一款面向家庭烹饪用户的美食菜谱管理App，以温暖治愈的橙米色调为视觉基调，融合新拟态（Neumorphism）与圆润卡片的现代设计语言。\\n\\n**核心功能模块：**\\n\\n• **首页（冰箱+菜单）** — 双栏卡片式布局，左侧展示冰箱内现有食材及数量，右侧推荐今日菜谱，顶部拍照/日历快捷入口，底部日记·首页·我的三大Tab导航\\n\\n**个人中心体系：**\\n• 用户主页 — 头像、使用时长、四大功能入口（饮食偏好/个人设置/存储空间/关于反馈）\\n• 饮食偏好设置 — 菜系、口味、菜量、人数四维偏好配置\\n• 个人信息编辑 — 昵称、日夜间模式切换、字体选择、存储空间管理\\n• 关于反馈页 — FAQ常见问题列表与可爱吉祥物形象\\n• 隐私设置 — 通讯录/麦克风/相册/剪贴板/位置/通知/相机/音频等权限管理\\n\\n**菜谱系统：**\\n• 菜谱列表 — 左侧数字导航栏（1-5）+ 右侧详情区，包含菜品封面图、名称、简介、难度标签（锅/笑脸/肉）、食材清单与分步骤图文说明\\n• 菜谱详情 — 大图展示 + 双列信息布局（左侧主料/辅料/调料，右侧详细步骤），完成按钮交互\\n• 视频播放 — 全屏视频播放器带播放控件\\n\\n**食材管理：**\\n• 食材清单 — 日期/人数/时间头部 + 表格式食材录入（品名+数量）\\n• 扫描识别 — 相机扫描框界面，支持拍照识别食材\\n\\n**社区互动：**\\n• 日记/菜单流 — 卡片式菜品分享列表（毛豆腐、白切鸡等），含收藏与图片预览功能\\n• 评论页面 — 用户评论头像+文字+配图的瀑布流展示\\n• 分享输入 — 文字输入框引导用户发布内容\\n\\n**启动体验：**\\n• 闪屏页 — 品牌图标（厨师帽+餐盖吉祥物）+ 品牌Slogan「炒青菜大火快炒，能锁住水分和营养」\\n\\n**设计亮点：**\\n- 统一的圆角卡片语言（大圆角胶囊按钮+圆角输入框+圆角图片容器）\\n- 新拟态风格的凸起/凹陷效果（按钮、卡片、输入框均带有柔和阴影层次）\\n- 温暖的橙色（#E8A87C）+ 米色（#F5E6D3）主色调，营造亲切的厨房氛围\\n- 清晰的信息层级：标题→副标题→正文→辅助文字的四级字号体系\\n- 完整的15+页面覆盖了App的核心用户旅程\\n\\n该作品完整呈现了从概念到落地的UI设计能力，包含用户画像构建、交互流程梳理、视觉规范制定到最终高保真原型输出的全链路工作。",
        software: ["Figma", "Photoshop", "ProtoPie"],
        role: "UI设计 · 界面落地 · 高保真原型 · 设计规范"
    },
    {
        id: 25,
        name: "原创插画作品集 — 手绘与数字绘画",
        category: "other",
        subCategory: "Illustration",
        year: "2025-2026",
        thumbnail: "assets/works/art-gallery/17-lighthouse.jpg",
        video: "",
        images: [
            "assets/works/art-gallery/01-interior-door.jpg",
            "assets/works/art-gallery/02-gothic-street.jpg",
            "assets/works/art-gallery/03-bathroom-sink.jpg",
            "assets/works/art-gallery/04-mountain-clouds.jpg",
            "assets/works/art-gallery/05-boy-orange-eyes.jpg",
            "assets/works/art-gallery/06-girl-orange-hair.png",
            "assets/works/art-gallery/07-purple-winged.jpg",
            "assets/works/art-gallery/08-green-haired.jpg",
            "assets/works/art-gallery/09-tree-path.jpg",
            "assets/works/art-gallery/10-orchid-room.jpg",
            "assets/works/art-gallery/11-street-scene.jpg",
            "assets/works/art-gallery/12-gas-mask-sitting.png",
            "assets/works/art-gallery/13-fantasy-green-dress.png",
            "assets/works/art-gallery/14-wolf-warrior.png",
            "assets/works/art-gallery/15-lion-dance-girl.png",
            "assets/works/art-gallery/16-red-hair-lady.png",
            "assets/works/art-gallery/17-lighthouse.jpg"
        ],
        description: "涵盖扁平风场景插画、动漫角色设计与传统元素融合的原创手绘作品集。",
        detailDescription: "这是一组跨越2024至2026年的个人原创插画与绘画作品合集，展现了从环境氛围插画到角色设计的多维度创作实践。\\n\\n**场景插画系列：** 以扁平化色块与纹理叠加为手法，探索室内空间（门廊、浴室、兰花窗景）、城市街景、自然景观（山峦云海、林间小径）等主题。每幅画面注重构图张力与色彩情绪的传达，通过有限色板构建出富有叙事感的视觉空间。\\n\\n**角色设计系列：** 包含多组风格化角色创作——从日系动漫风格的少年少女（互补色配色实验系列），到带有奇幻色彩的狼耳剑士、醒狮少女、红发贵妇等独立角色设计。这些作品探索了不同画风下的角色塑造方法，包括动态姿态构图、服饰细节刻画以及个性化配色方案。\\n\\n**特色作品：**\\n• **醒狮少女** — 将中国传统舞狮文化与现代二次元美学融合的角色设计，红色调为主，充满动感与节日气息\\n• **傲女（狼耳剑士）** — 东方武侠风格的角色立绘，灰白长发配狼耳设定，手持双刀，气质冷峻\\n• **004 红发贵妇** — 哥特式长裙礼服角色设计，以红蓝渐变发色和融化效果为视觉亮点\\n• **灯塔** — 扁平风格海景建筑插画，红色灯塔与蓝色海面形成强烈对比\\n\\n这批作品记录了在数位绘画领域的持续探索——从早期的临摹练习到逐步建立个人视觉语言的完整成长轨迹。",
        software: ["Photoshop", "Procreate", "Clip Studio Paint"],
        role: "原创插画 · 角色设计 · 场景绘制"
    },
    {
        id: 24,
        name: "刀马旦 — 原画还原ZBrush雕刻",
        category: "modeling",
        subCategory: "Character",
        year: "2025",
        thumbnail: "assets/works/daomadan/render-daomadan-006.png",
        video: "assets/works/daomadan/hero-video.mp4",
        images: [
            "assets/works/daomadan/render-final.png",
            "assets/works/daomadan/render-v2-full.png",
            "assets/works/daomadan/render-full-front.png",
            "assets/works/daomadan/render-v2-alt.png",
            "assets/works/daomadan/render-full-wide.png",
            "assets/works/daomadan/render-full-side.png",
            "assets/works/daomadan/render-full-dark.png",
            "assets/works/daomadan/render-angle3q.png",
            "assets/works/daomadan/render-girl-closeup.png",
            "assets/works/daomadan/render-v2-girl.png",
            "assets/works/daomadan/render-v2-front2.png",
            "assets/works/daomadan/render-v2-girl-face.png",
            "assets/works/daomadan/render-mask-hands.png",
            "assets/works/daomadan/render-giant-hands.png",
            "assets/works/daomadan/render-boots.png",
            "assets/works/daomadan/render-boots-detail.png",
            "assets/works/daomadan/render-cloak-back.png",
            "assets/works/daomadan/render-cloak-side.png",
            "assets/works/daomadan/clay-turntable.png",
            "assets/works/daomadan/clay-compare.png",
            "assets/works/daomadan/clay-front.png",
            "assets/works/daomadan/clay-detail.png",
            "assets/works/daomadan/zbrush-ui.png",
            "assets/works/daomadan/concept.png"
        ],
        description: "大二下学期基于原画参考完成的ZBrush高精度雕刻作品——巨型面罩守护者与持面具少女的双人组像，从原画分析到最终渲染的完整雕刻流程。",
        detailDescription: "刀马旦是大二下学期以小红书原画（208号）为参照完成的高精度数字雕塑作品，核心场景是一位身形巨大的面罩守护者与一位手持戏曲面具的少女形成的双人组像。\\\\n\\\\n原画解读：原画呈现了极具东方神秘主义色彩的构图——巨型人物身着宽大斗篷式长袍，面部被复杂的图腾式面罩遮盖，怀中坐着一位佩戴京剧脸谱的少女。整体色调以暗褐、靛蓝、朱红为主，辅以金线刺绣和毛绒装饰等丰富材质层次。\\\\n\\\\n雕刻流程：\\\\n• 原画分析 — 解构双人体型比例（约3:1）、服饰结构、材质分布与姿态关系\\\\n• Blockout搭建 — 在ZBrush中用基础几何体确定双人构图与大形比例\\\\n• 巨人雕刻 — 雕刻宽大斗篷的布料褶皱、面罩纹路、枯手细节、指甲质感\\\\n• 少女雕刻 — 刻画面部五官、发型动态、戏服刺绣纹理、流苏装饰\\\\n• 道具雕刻 — 戏曲脸谱（手中持有+耳侧悬挂）、虎头护胸饰、金属护腿\\\\n• 材质分区 — 为Substance Painter导出准备：布料/皮革/金属/皮肤/木质等区域划分\\\\n• 渲染输出 — KeyShot/UE多角度渲染，含正面、侧面、背面、特写等多机位展示\\\\n\\\\n该作品的挑战在于处理超大比例差的双人交互关系，以及在单一雕塑中融合中式传统元素（戏曲、刺绣、图腾）与现代数字雕刻技法。\\\\n\\\\n技术规格：ZBrush高模（千万级面数），含完整UV拆分与材质烘焙。",
        software: ["ZBrush", "Blender", "KeyShot", "Substance Painter"],
        role: "原画还原 · 高精雕刻 · 角色建模 · 材质渲染"
    },
    {
        id: 11,
        name: "DIMENSION — 手机作业综合动画",
        category: "animation",
        subCategory: "Motion Graphics",
        year: "2026",
        thumbnail: "assets/works/anim-1/OfficeA_P_0310.png",
        video: "assets/works/anim-1/video.mp4",
        images: [
            "assets/works/anim-1/OfficeA_P_0310.png",
            "assets/works/anim-1/OfficeA_P_0025.png",
            "assets/works/anim-1/3-1_00285.png",
            "assets/works/anim-1/4-1_00403.png",
            "assets/works/anim-1/4-2_00478.png",
            "assets/works/anim-1/4-4_00529.png",
            "assets/works/anim-1/3-1_1.png",
            "assets/works/anim-1/3-1_2.png",
            "assets/works/anim-1/3-1_3.png",
            "assets/works/anim-1/3-1_未标题-1.png",
            "assets/works/anim-1/3-2_0.png",
            "assets/works/anim-1/3-2_1.png",
            "assets/works/anim-1/3-2_2.png",
            "assets/works/anim-1/4-1_0.png",
            "assets/works/anim-1/4-1_01.png",
            "assets/works/anim-1/4-1_02.png",
            "assets/works/anim-1/4-1_03.png",
            "assets/works/anim-1/4-1_1.png",
            "assets/works/anim-1/4-1_2.png",
            "assets/works/anim-1/4-2_0.png",
            "assets/works/anim-1/4-2_1.png",
            "assets/works/anim-1/4-3_0.png",
            "assets/works/anim-1/4-3_0076.png",
            "assets/works/anim-1/4-3_1.png",
            "assets/works/anim-1/4-3_2.png",
            "assets/works/anim-1/4-3_3.png",
            "assets/works/anim-1/4-3_4.png",
            "assets/works/anim-1/4-3_5.png",
            "assets/works/anim-1/4-3_6.png",
            "assets/works/anim-1/4-3_7.png",
            "assets/works/anim-1/5_0.png",
            "assets/works/anim-1/5_1.png"
        ],
        description: "以「DIMENSION」为主题的手机综合设计动画，融合 3D 角色场景与波普艺术风格视觉。",
        detailDescription: "该项目以\"DIMENSION（维度）\"为核心概念，探索平行宇宙中不同维度的手机体验。视频结合了高精度 3D 角色、机械义肢交互场景，以及多组波普艺术风格的静态视觉方案。通过强烈的色彩对比（橙红 / 青蓝）、粗犷的排版字体和半调网点纹理，构建出一个介于现实与虚构之间的视觉世界。",
        software: ["After Effects", "Cinema 4D", "Photoshop", "Illustrator"],
        role: "动态设计 · 3D角色 · 视觉设计"
    },
    {
        id: 12,
        name: "MORTROPOLIS — 躯体城市角色设计",
        category: "other",
        subCategory: "Character Design",
        year: "2025",
        thumbnail: "assets/works/mortropolis/01_poster_main.png",
        video: "",
        images: [
            "assets/works/mortropolis/01_poster_main.png",
            "assets/works/mortropolis/00_worldview.png",
            "assets/works/mortropolis/02_trio_split.png",
            "assets/works/mortropolis/03_emotion_male.png",
            "assets/works/mortropolis/04_male_turnaround.png",
            "assets/works/mortropolis/05_mayor_fraternity.png",
            "assets/works/mortropolis/06_female_arms.png",
            "assets/works/mortropolis/07_knight_noble.png",
            "assets/works/mortropolis/08_knight_turnaround.png",
            "assets/works/mortropolis/09_end_screen.png",
            "assets/works/mortropolis/10_prop_female.png",
            "assets/works/mortropolis/11_prop_male.png",
            "assets/works/mortropolis/12_3d_head.png",
            "assets/works/mortropolis/13_3d_fullbody.png",
            "assets/works/mortropolis/14_3d_detail.png",
            "assets/works/mortropolis/15_render_004.png",
            "assets/works/mortropolis/16_render_005.png",
            "assets/works/mortropolis/17_render_01.png",
            "assets/works/mortropolis/18_render_02.png",
            "assets/works/mortropolis/19_render_03.png",
            "assets/works/mortropolis/20_final_male.png",
            "assets/works/mortropolis/21_final_knight.png",
            "assets/works/mortropolis/22_final_mayor.png",
            "assets/works/mortropolis/23_final_citylord.png"
        ],
        description: "以「MORTROPOLIS（躯体城市）」为主题的完整角色设计项目，涵盖世界观构建、三主角设定、2D插画与3D渲染全流程。",
        detailDescription: "MORTROPOLIS 是一个设定在近未来反乌托邦世界的原创角色设计项目。故事背景构建了一个以\"完美躯壳\"为信仰的赛博朋克都市——文明崩溃后幸存的人类通过意识提取与机械义肢技术追求永生。\\n\\n项目包含三位核心角色：\\n• **EMOTION（情绪）** — 红衣机械臂少年，底层拾荒者，代表反抗与自由意志\\n• **FRATERNITY（博爱）** — 圣母般的城市统治者，六臂机械神像，象征虚假救赎\\n• **KNIGHTNOBLE（骑士贵胄）** — 白发铠甲贵族，旧时代遗民，代表秩序与压迫\\n\\n工作流程涵盖：世界观架构图绘制 → 角色概念草图 → 完成级2D插画 → ZBrush高模雕刻 → KeyShot/渲染器最终输出。项目同时包含道具设计、三视图设定及完整PDF文档。",
        software: ["Photoshop", "ZBrush", "KeyShot", "Blender", "Illustrator"],
        role: "角色设计 · 概念设计 · 3D建模 · 渲染",
        pdf: "assets/works/mortropolis/MORTROPOLIS.pdf"
    },
    {
        id: 18,
        name: "商业雕刻委托 — ZBrush 数字雕塑作品集",
        category: "modeling",
        subCategory: "Props",
        year: "2025",
        thumbnail: "assets/works/commercial-2025/ashtray-square-v1.jpg",
        video: "",
        images: [
            "assets/works/commercial-2025/ashtray-square-v1.jpg",
            "assets/works/commercial-2025/ashtray-round-v1.jpg",
            "assets/works/commercial-2025/ashtray-top-square.jpg",
            "assets/works/commercial-2025/ashtray-top-round.jpg",
            "assets/works/commercial-2025/ashtray-side-a.jpg",
            "assets/works/commercial-2025/ashtray-side-b.jpg",
            "assets/works/commercial-2025/ashtray-bottom-sq.jpg",
            "assets/works/commercial-2025/ashtray-bottom-round.jpg",
            "assets/works/commercial-2025/ashtray-wireframe.png",
            "assets/works/commercial-2025/angel-figurine.png",
            "assets/works/commercial-2025/star-character.png"
        ],
        description: "大二下学期接到的多笔商业雕刻委托，涵盖中式烟灰缸、天使摆件、IP角色等实物级数字雕塑。",
        detailDescription: "大二下学期独立承接的多项ZBrush商业雕刻委托项目，客户需求均为可用于3D打印或模具生产的实物级高精度模型。\\n\\n包含三件不同类型的委托作品：\\n\\n① 中式云纹烟灰缸 — 根据客户提供的草图进行中式传统纹样（祥云、山水）的浮雕雕刻，完成方型与圆型两款设计，要求细节精致、边缘光滑，适合树脂或陶瓷材质打印。\\n\\n② 天使摆件 — 球形底座上的天使造型摆件雕刻，重点刻画翅膀的羽毛层次与球体的圆润过渡，需兼顾美观与结构强度。\\n\\n③ 星星IP角色 — 卡通星星造型的角色设计雕刻，含四视图展示，需保持可爱风格的同时保证各部件比例准确。\\n\\n这些委托锻炼了从客户沟通到最终交付的完整商业流程能力。",
        software: ["ZBrush"],
        role: "商业委托 · 数字雕塑 · 3D打印模型"
    },
    {
        id: 16,
        name: "青发赛博少女 — 角色原创设计与全流程制作",
        category: "modeling",
        subCategory: "Character",
        year: "2024",
        thumbnail: "assets/works/cyber-girl/headshot.png",
        video: "",
        images: [
            "assets/works/cyber-girl/headshot.png",
            "assets/works/cyber-girl/concept.png",
            "assets/works/cyber-girl/render-t-pose.png",
            "assets/works/cyber-girl/rig-side.png",
            "assets/works/cyber-girl/rig-back.png",
            "assets/works/cyber-girl/zb-clay01.jpg",
            "assets/works/cyber-girl/zb-clay02.jpg",
            "assets/works/cyber-girl/zb-clay03.jpg",
            "assets/works/cyber-girl/render-rig01.png",
            "assets/works/cyber-girl/render-rig02.png",
            "assets/works/cyber-girl/render-face01.png",
            "assets/works/cyber-girl/render-pose01.png",
            "assets/works/cyber-girl/render-pose02.png",
            "assets/works/cyber-girl/render-walk.png"
        ],
        description: "大一下学期原创角色「青发赛博少女」的全流程制作——从概念设计、ZBrush雕刻到Blender绑定渲染。",
        detailDescription: "青发赛博少女是大一下学期独立完成的原创角色全流程作品，涵盖从二维概念到三维可动角色的完整管线。\\n\\n角色设定：一位拥有标志性青绿色短发的年轻女性，身穿红色夹克与机能风格服装，腿部装配机械义肢，整体呈现赛博朋克与街头风格的融合美学。\\n\\n完整制作流程：\\n• 概念设计 — 绘制风格化立绘，确立角色配色方案（红/黑/灰/青绿）与剪影特征\\n• ZBrush 雕刻 — 从基础大型到高精度细节的全身数字雕塑，重点刻画服装褶皱与机械义肢结构\\n• 拓扑与UV — 生成适合绑定的低模布线结构\\n• Blender 绑定 — 使用 Auto-Rig Pro 进行专业级骨骼绑定，支持面部表情系统\\n• 材质与渲染 — 在 Blender 中完成材质贴图与多角度最终渲染\\n\\n该作品探索了游戏角色制作的标准管线，从静态雕刻走向动态可操控角色的完整实践。",
        software: ["ZBrush", "Blender", "Photoshop"],
        role: "原创设计 · 数字雕刻 · 骨骼绑定 · 渲染"
    },
    {
        id: 15,
        name: "杀手 — 角色原创设计雕塑",
        category: "modeling",
        subCategory: "Character",
        year: "2024",
        thumbnail: "assets/works/killer-girl/headshot.jpg",
        video: "",
        images: [
            "assets/works/killer-girl/headshot.jpg",
            "assets/works/killer-girl/turnaround.jpg",
            "assets/works/killer-girl/concept.png"
        ],
        description: "大一下学期原创角色「杀手」的完整设计与ZBrush三维雕刻还原。",
        detailDescription: "杀手是大一下学期独立完成的原创角色设计作品——从概念草图到ZBrush数字雕塑的全流程创作。\\n\\n角色设定：一位红发编辫少女，身着哥特洛丽塔风格的暗红与黑色服装，手持巨型战斧作为武器。外表甜美却暗藏杀机，这种\"反差感\"是设计的核心表达。\\n\\n制作流程：\\n• 概念设定 — 绘制角色全身立绘，确定服装配色与道具细节\\n• ZBrush 头部雕刻 — 重点塑造面部特征与红发辫子的体积结构\\n• 全身三视图 — 完整的正/侧/背三视图展示服装层次与配饰细节\\n\\n这是从二维原画设计走向三维角色建模的重要练习，探索了原创角色的完整制作管线。",
        software: ["ZBrush", "Photoshop"],
        role: "原创设计 · 概念插画 · 数字雕刻"
    },
    {
        id: 13,
        name: "剪刀圣母 — 角色数字雕塑",
        category: "modeling",
        subCategory: "Character",
        year: "2025",
        thumbnail: "assets/works/scissor-madonna/portfolio.png",
        video: "",
        images: [
            "assets/works/scissor-madonna/portfolio.png",
            "assets/works/scissor-madonna/01.jpg",
            "assets/works/scissor-madonna/02.jpg",
            "assets/works/scissor-madonna/03.jpg",
            "assets/works/scissor-madonna/04.jpg",
            "assets/works/scissor-madonna/concept.png"
        ],
        description: "以「剪刀圣母」为题的原创角色数字雕塑，融合宗教圣洁美学与暗黑哥特风格。",
        detailDescription: "剪刀圣母是一个原创角色设计作品，灵感来源于宗教圣像艺术与超现实主义暗黑美学的碰撞。\\n\\n角色外表呈现一位头戴荆棘冠冕、身披珠链长袍的圣洁女性形象，面容宁静、姿态优雅；然而她的背部却生长出由骨骼构成的巨型剪刀状肢体，如同蜘蛛般向外延伸——这种\"表象神圣，内里残酷\"的二元对立是本设计的核心表达。\\n\\n制作流程：\\n• 概念草图 → 确定角色比例与剪影特征\\n• ZBrush 基础大型雕刻 → 确立整体体量与动态\\n• 高精度细节雕刻 — 重点刻画皇冠纹样、珠链垂坠感、骨骼剪刀的解剖结构\\n• 多角度渲染输出（正/背/侧/特写）配合概念插画作为最终展示\\n\\n该作品探索了数字雕塑中\"美与恐怖共存\"的表现可能性，通过细腻的面部刻画与令人不安的肢体变异形成强烈的视觉张力。",
        software: ["ZBrush", "Photoshop"],
        role: "概念设计 · 数字雕刻 · 渲染"
    },
    {
        id: 14,
        name: "原画临摹雕刻 — ZBrush 数字雕塑",
        category: "modeling",
        subCategory: "Character",
        year: "2025",
        thumbnail: "assets/works/modeling-work-2/portfolio.png",
        video: "",
        images: [
            "assets/works/modeling-work-2/portfolio.png",
            "assets/works/modeling-work-2/01.jpg",
            "assets/works/modeling-work-2/02.jpg",
            "assets/works/modeling-work-2/03.jpg",
            "assets/works/modeling-work-2/04.jpg",
            "assets/works/modeling-work-2/zb-r1.png",
            "assets/works/modeling-work-2/zb-r2.png"
        ],
        description: "大二上学期ZBrush原画临摹雕刻练习，依据原画设定进行角色肖像与生物的三维还原雕刻。",
        detailDescription: "大二上学期基于原画设定进行的ZBrush临摹雕刻练习。\\n\\n以二维原画为参考，在三维空间中还原角色肖像结构与生物体态，重点训练「从平面到立体」的造型转换能力。\\n\\n制作要点：\\n• 原画分析 — 剖析设定图的比例、光影与结构关系\\n• ZBrush 大型搭建 — 从基础几何体逐步构建角色体块\\n• 细节雕刻 — 面部解剖、肌肉走向、皮肤纹理的精细化处理\\n• 多角度渲染 → Photoshop后期排版，呈现完整的临摹作品集",
        software: ["ZBrush", "Photoshop"],
        role: "原画临摹 · 数字雕刻 · 渲染 · 作品集排版"
    },
    {
        id: 23,
        name: "赛博朋克城市与巨型机械人偶",
        category: "scenedesign",
        subCategory: "Environment",
        year: "2024",
        thumbnail: "assets/works/cyberpunk-city/render-hero.png",
        video: "assets/works/cyberpunk-city/hero-video.mp4",
        images: [
            "assets/works/cyberpunk-city/render-hero.png",
            "assets/works/cyberpunk-city/render-character.png",
            "assets/works/cyberpunk-city/render-window.png",
            "assets/works/cyberpunk-city/render-wide.png",
            "assets/works/cyberpunk-city/render-alley.png",
            "assets/works/cyberpunk-city/render-grid.png",
            "assets/works/cyberpunk-city/render-portal.png",
            "assets/works/cyberpunk-city/render-street.png",
            "assets/works/cyberpunk-city/concept.png",
            "assets/works/cyberpunk-city/asset-skyscrapers.png",
            "assets/works/cyberpunk-city/asset-buildings.png",
            "assets/works/cyberpunk-city/asset-characters.png"
        ],
        description: "大二上学期原创赛博朋克城市场景——以巨型机械人偶头为核心地标，构建完整的未来都市夜景叙事空间。",
        detailDescription: "「小爷巨作」是大二上学期独立完成的原创赛博朋克场景作品，以一个废弃的巨型机械人偶头部为视觉中心，围绕其构建了完整的未来都市生态。\\n\\n核心概念：一座被遗忘的巨型人形机械装置静卧在城市边缘——它曾是某种工业时代的产物或宗教偶像，如今只剩下布满裂痕的陶瓷面庞和两盏仍在微弱发光的蓝色电子眼。周围是拥挤的贫民窟建筑、闪烁的全息广告牌、游弋的光海豚投影，以及一位驻足凝视它的赛博格旅人。\\n\\n制作规模：\\n• 模块化摩天楼资产 — 8+栋风格各异的赛博朋克高层，每栋配备可自定义的全息广告牌系统\\n• 贫民窟低层建筑 — 16+栋自建/违章搭建风格的底层建筑，体现城市底层的生存状态\\n• 角色资产库 — 可拆分的角色模块化部件（头饰、躯干、四肢、装备），支持快速组合不同角色外观\\n• 核心地标 — 巨型机械人偶头部的完整建模与材质，含裂纹细节与发光眼系统\\n• 环境叙事道具 — 管道、空调外机、涂鸦、垃圾袋、塑料凳等大量生活化细节\\n\\n技术实现：\\n• UE5引擎 Lumen全局光照 + 体积雾营造雨夜氛围\\n• 全息投影材质（光海豚、广告牌）使用透明度遮罩+自发光着色器\\n• 湿润地面反射效果增强霓虹色彩的表现力\\n• 多机位电影级镜头设计（角色过肩、窗框构图、广角全景等）\\n\\n这是从概念草图到完整资产库再到最终渲染的大型场景项目，展现了独立构建复杂游戏关卡环境的能力。",
        software: ["Blender", "Unreal Engine 5", "Substance Painter"],
        role: "原创场景 · 关卡设计 · 模块化资产 · 渲染"
    },
    {
        id: 22,
        name: "修车工坊 — 照片还原场景制作",
        category: "scenedesign",
        subCategory: "Environment",
        year: "2025",
        thumbnail: "assets/works/garage-workshop/render-final.png",
        video: "",
        images: [
            "assets/works/garage-workshop/render-final.png",
            "assets/works/garage-workshop/render-wide.png",
            "assets/works/garage-workshop/car-detail-final.png",
            "assets/works/garage-workshop/car-detail-v1.png",
            "assets/works/garage-workshop/render-v1.png",
            "assets/works/garage-workshop/whitebox.png",
            "assets/works/garage-workshop/ai-reference.png"
        ],
        description: "大二下学期基于AI概念参考与真实照片进行的三维工坊场景还原——锈迹斑斑的甲壳虫汽车与充满生活气息的老式修车车间。",
        detailDescription: "修车工坊是大二下学期以AI生成图像为视觉参考、结合真实照片细节完成的环境还原作品，核心目标是在引擎中重建一个充满叙事感的旧式汽车修理车间。\\n\\n场景核心：一辆停放在车间中央的复古甲壳虫汽车，车身覆盖着大面积的青绿色底漆与橙红色锈迹，仿佛在这里沉睡了数十年。周围是砖墙、铁制楼梯、工具挂板、油桶、工作台等典型工坊元素，天窗透入的自然光与室内灯光交织，营造出温暖而怀旧的氛围。\\n\\n制作流程：\\n• AI参考分析 — 使用AI生成的仓库/工坊风格插画作为构图、光影和质感的基础参照\\n• 白盒搭建（Blockout）— 在UE中用基础几何体确定空间比例、相机角度与光源方向\\n• 场景建模 — Blender制作墙体、楼梯、门窗、工具架、工作台等硬表面资产\\n• 汽车资产 — 制作高精度复古甲壳虫模型，重点处理锈迹剥落的材质层次\\n• 环境道具 — 油桶、灭火器、喷漆罐、扳手挂板等细节道具丰富场景\\n• 材质系统 — Substance/UE中处理砖墙风化、金属锈蚀、地面污渍等 aged 材质\\n• 灯光渲染 — 天窗主光源 + 点光源补光 + 体积雾，多轮迭代优化最终氛围\\n\\n该作品的特色在于从AI概念图到三维实景的完整转化流程，以及汽车锈迹材质的高精度表现。",
        software: ["Blender", "Unreal Engine", "Substance Painter"],
        role: "场景设计 · 照片还原 · 地编 · 材质渲染"
    },
    {
        id: 21,
        name: "树鸟楼人 — 怪兽大厦天井场景",
        category: "scenedesign",
        subCategory: "Environment",
        year: "2025",
        thumbnail: "assets/works/tree-bird-building/render-final.png",
        video: "",
        images: [
            "assets/works/tree-bird-building/render-final.png",
            "assets/works/tree-bird-building/render-v4.png",
            "assets/works/tree-bird-building/render-v3.png",
            "assets/works/tree-bird-building/render-v2.png",
            "assets/works/tree-bird-building/render-v1.png",
            "assets/works/tree-bird-building/concept.png"
        ],
        description: "大二下学期原创史诗级场景——港式怪兽大厦天井中，巨型红怪与坠落之人的垂直构图叙事场景。",
        detailDescription: "树鸟楼人是大二下学期独立完成的原创概念场景作品，以香港鲗鱼涌怪兽大厦为灵感来源，融合超现实主义元素创作出的垂直叙事空间。\\n\\n场景概念：俯瞰视角下，五栋密集的旧式唐楼围成一个深邃的天井——楼体表面布满空调外机、防盗网和攀爬的藤蔓植物。天井底部，一尊巨大的红色多臂怪物正向上伸展，而画面中段，一个渺小的人形正在坠落。四者——树、鸟、楼、人，构成了画面的完整叙事链条。\\n\\n制作流程：\\n• 概念草图 — 手绘确定「树·鸟·楼·人」四元素在垂直构图中的位置关系与视觉权重\\n• 楼宇建模 — 使用模块化方式搭建五栋住宅楼的立面细节（窗户、阳台、外机支架）\\n• 天井环境 — 制作植被覆盖系统、藤蔓生长效果与大气雾气层\\n• 怪物资产 — 雕刻红色多臂巨怪的有机形态，赋予其压迫性的体积感\\n• 角色姿态 — 调整坠落人物的肢体动作以传递失重感与无助感\\n• UE灯光与氛围 — 自上而下的体积光穿透雾气层，配合暗角效果强化纵深感\\n• 迭代渲染 — 从基础光照到最终合成的五个版本持续优化氛围表现\\n\\n该作品探索了超大尺度场景的构建方法，以及如何通过构图比例（巨怪 vs 渺小的人 vs 更渺小的建筑）来制造视觉冲击力。",
        software: ["Blender", "ZBrush", "Unreal Engine"],
        role: "原创场景 · 概念设计 · 地编 · 灯光渲染"
    },
    {
        id: 20,
        name: "窗口2 — 原创氛围场景设计",
        category: "scenedesign",
        subCategory: "Environment",
        year: "2025",
        thumbnail: "assets/works/window2/render-final.png",
        video: "",
        images: [
            "assets/works/window2/render-final.png",
            "assets/works/window2/render-v3.png",
            "assets/works/window2/render-v2.png",
            "assets/works/window2/render-v1.png",
            "assets/works/window2/editor.png",
            "assets/works/window2/concept.png"
        ],
        description: "大二下学期原创氛围场景作品——废弃房间中独坐的少年，从概念草图到引擎渲染的完整叙事场景构建。",
        detailDescription: "窗口2是大二下学期独立完成的原创场景设计作品，以「孤独」与「等待」为核心情感主题。\\n\\n场景叙事：一间被时间遗忘的破旧房间——剥落的墙皮、布满蛛网的窗户角落、散落的杂物与一辆旧自行车。一个少年背对镜头坐在房间一角，凝视着窗外透进来的微弱光线。画面没有直接展示少年的表情，但通过姿态和环境传递出强烈的孤独感与故事性。\\n\\n完整创作流程：\\n• 概念构思 — 手绘草图确定构图：低角度仰视 + 少年背影作为前景引导视线至窗光\\n• 场景建模 — 在Blender中搭建房间结构（墙体、门窗、地面）并雕刻破损细节\\n• 资产制作 — 制作自行车、床铺、散落物品等环境叙事道具\\n• 材质与 aged 处理 — 墙皮脱落纹理、灰尘堆积效果、蛛网粒子系统\\n• UE引擎灯光 — 以单一光源（窗口自然光）为主光源，配合室内补光灯营造电影级明暗对比\\n• 迭代渲染 — 从基础光照到最终合成的多版本迭代优化\\n\\n该作品探索了「用环境讲故事」的地编核心能力，通过光影、材质和构图的协同营造沉浸式的情绪体验。",
        software: ["Blender", "Unreal Engine"],
        role: "原创场景 · 概念设计 · 地编 · 灯光渲染"
    },
    {
        id: 19,
        name: "街角水果店 — 照片还原场景制作",
        category: "scenedesign",
        subCategory: "Environment",
        year: "2024",
        thumbnail: "assets/works/street-corner/render.jpg",
        video: "",
        images: [
            "assets/works/street-corner/render.jpg",
            "assets/works/street-corner/reference.jpg"
        ],
        description: "大一下学期基于真实街景照片进行的三维场景还原——东南亚风格街角水果店，从参考图分析到引擎渲染的完整地编练习。",
        detailDescription: "街角水果店是大一下学期以真实街景照片为参照完成的环境还原作品。\\n\\n原始参考是一张充满生活气息的街角照片：斑驳的黄色墙面上挂着红黄条纹遮阳篷，门前摆满水果摊位，空调外机、路牌、黑板、塑料凳等细节构成了极具真实感的市井空间。\\n\\n制作流程：\\n• 参考分析 — 解构照片中的建筑结构、材质分布、光影关系与色彩基调\\n• 模块化搭建 — 使用Blender/ZBrush制作墙面、遮阳篷、门窗、水果箱、空调外机等独立资产\\n• 场景布置 — 按照照片构图摆放资产，调整比例与位置关系\\n• 材质制作 — 重点处理墙面剥落、污渍、金属锈迹等 aged 材质表现\\n• 灯光渲染 — 模拟自然光照条件（树荫下的柔和散射光），在引擎中输出最终画面\\n\\n该作品的核心理念是「观察→理解→重现」，训练从现实世界提取视觉信息并在三维空间中重建的能力。",
        software: ["Blender", "Unreal Engine"],
        role: "场景设计 · 照片还原 · 地编 · 渲染"
    },
    {
        id: 17,
        name: "掌中之城 — 洞穴场景与概念合成",
        category: "scenedesign",
        subCategory: "Environment",
        year: "2024",
        thumbnail: "assets/works/cave-city/final.jpg",
        video: "",
        images: [
            "assets/works/cave-city/final.jpg",
            "assets/works/cave-city/final-v2.jpg",
            "assets/works/cave-city/composition-wireframe.png",
            "assets/works/cave-city/cave-terrain.png"
        ],
        description: "大一下学期原创地编作品——洞穴中的机械人手托赛博朋克城市，探索环境雕刻与概念合成的结合。",
        detailDescription: "掌中之城是大一下学期独立完成的环境艺术原创作品，将地形雕刻、角色摆放与概念合成融为一体。\\n\\n场景概念：幽深洞穴之中，一位赛博机械人双手捧着一座微缩的霓虹城市——巨大的手掌与渺小的城市形成强烈的尺度对比，表达\"掌控与被掌控\"的哲学意象。\\n\\n制作流程：\\n• 场景规划 — 确定洞穴构图与光源方向，设计人物姿态与城市位置关系\\n• 地形雕刻 — 在ZBrush中雕刻洞穴岩壁的自然起伏与岩石细节，营造真实的空间纵深感\\n• 角色与资产搭建 — 放置机械角色模型并调整手部姿势以承载城市\\n• 材质与渲染 — 调整岩石材质、雾气氛围与城市霓虹光效\\n• 后期合成 — Photoshop最终调色，增强光影对比与科幻氛围\\n\\n该作品尝试突破传统地编的范畴，将环境作为叙事载体，通过空间尺度对比传递情感。",
        software: ["ZBrush", "Blender", "Photoshop"],
        role: "场景设计 · 地形雕刻 · 概念合成 · 渲染"
    },

];

/* 分类定义 */
const CATEGORIES = [
    { id: 'all', name: '全部', label: '主分类' },
    { id: 'modeling', name: '建模', subs: ['Character', 'Prop', 'Environment'] },
    { id: 'scenedesign', name: '场景设计', subs: ['Interior', 'Exterior', 'Concept'] },
    { id: 'animation', name: '动画', subs: ['Character Animation', 'Motion Graphics'] },
    { id: 'other', name: '其他', subs: ['Character Design', 'Sculpting', 'Texture Studies', 'Illustration', 'UI Design'] }
];
